### ISSUE TITLE
Проверить поведение решателя для случая первого аргумента не графа

### ISSUE THREAD

**Issue by KovalM** [gt-ostis-dev/gt-knowledge-processing-machine#6]
1) Проверить, что выдаст решатель, если первый аргумент не является графом по структуре, но является им по определению(добавлен в множество concept_graph)
2) Проверить, что выдаст решатель, если первый аргумент является графом по структуре, но не является им по определению(не добавлен в множество concept_graph)

Тестировать нужно для любой задачи, которую сейчас может решить решатель(прим. Проверка графа на свзность)

**Comment by FULLXOACINC** [comment]
Он не хочет работать со структурой которая не принадлежит к concept_graph,а если у нас структура принадлежит к concept_graph,но такой не является ,то он просто игнорирует все лишнее
